---
- hosts: localhost
  vars:
    hostname: "vcenter.ansible.local"
    esxihostname: "esxi.ansible.local"
    username: "user5@vsphere.local"
    password: "Password1!"
    nfs_user: "user5"
    portgroup_name: "vlan105"
    vlan_id: "105"
  tasks:
  - name: Add NFS Storage ESXi
    vmware_host_datastore:
      hostname: "{{ hostname }}"
      username: "{{ username }}"
      password: "{{ password }}"
      esxi_hostname: "{{ esxihostname }}"
      datastore_name: "datastore_{{ nfs_user }}"
      datastore_type: "nfs"
      nfs_server: "storage.ansible.local"
      nfs_path: "/storage/{{ nfs_user }}"
      nfs_ro: "no"
      state: "present"
      validate_certs: "False"
    delegate_to: "localhost"

  - name: Add a PortGroup to VMware vSwitch
    vmware_portgroup:
      hostname: "{{ hostname }}"
      username: "{{ username }}"
      password: "{{ password }}"
      validate_certs: False
      switch_name: "vSwitch0"
      esxi_hostname: "{{ esxihostname }}"
      portgroup_name: "{{ portgroup_name }}"
      vlan_id: "{{ vlan_id }}"
    delegate_to: localhost

  - name: Clone fedora 31 to userx webserver
    vmware_guest:
      hostname: "{{ hostname }}"
      username: "{{ username }}"
      password: "{{ password }}"
      validate_certs: "False"
      name: "webserver_{{ nfs_user }}"
      template: "_TEMP_fedora31"
      datacenter: "Datacenter"
      folder: "/"
      state: "poweredon"
      hardware:
        memory_mb: "1024"
        num_cpus: "1"
      disk:
      - size_gb: "16"
        type: "thin"
        datastore: "datastore1"
      - size_gb: "2"
        type: "thin"
        datastore: "datastore_{{ nfs_user }}"
      networks:
      - name: "{{ portgroup_name }}"
      wait_for_ip_address: "yes"
    register: "webserver"

    # Prepare ansible for webserver
  - name: Set Fact webserver_ip_fact
    set_fact:
     webserver_ip_fact: "{{ webserver.instance.ipv4 }}"

  - name: IP address info
    debug:
      msg: "{{ webserver_ip_fact }}"

  - name: Add ansibleserver to ssh known_hosts
    shell: "ssh-keyscan -t ecdsa {{ webserver_ip_fact }}  >> /home/{{ ansible_user_id }}/.ssh/known_hosts"